'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("iBMSC.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Collapse() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Collapse", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ConvertNotes() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ConvertNotes", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ConvertNotesH() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ConvertNotesH", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ConvertNotesHV() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ConvertNotesHV", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ConvertNotesL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ConvertNotesL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ConvertNotesN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ConvertNotesN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ConvertNotesV() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ConvertNotesV", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property CursorResizeDown() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("CursorResizeDown", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property CursorResizeLeft() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("CursorResizeLeft", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property CursorResizeRight() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("CursorResizeRight", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Expand() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Expand", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon2_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon2_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon2_16_highlight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon2_16_highlight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageError() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageError", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lgheight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lgheight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lgpartition() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lgpartition", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lgsub() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lgsub", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lgwidth() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lgwidth", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        '''&lt;iBMSC Major=&quot;3&quot; Minor=&quot;1&quot; Build=&quot;0&quot;&gt;
        '''    &lt;Columns&gt;
        '''        &lt;Column Index=&quot;0&quot; Width=&quot;50&quot; Title=&quot;Measure&quot; NoteColor=&quot;0&quot; TextColor=&quot;-16711681&quot; LongNoteColor=&quot;0&quot; LongTextColor=&quot;-16711681&quot; BG=&quot;0&quot; /&gt;
        '''        &lt;Column Index=&quot;1&quot; Width=&quot;60&quot; Title=&quot;SCROLL&quot; NoteColor=&quot;0&quot; TextColor=&quot;-65536&quot; LongNoteColor=&quot;0&quot; LongTextColor=&quot;-65536&quot; BG=&quot;0&quot; /&gt;
        '''        &lt;Column Index=&quot;2&quot; Width=&quot;60&quot; Title=&quot;BPM&quot; NoteColor=&quot;0&quot; TextColor=&quot;-65536&quot; LongNoteColor=&quot;0&quot; LongTextColor=&quot;-65536&quot; BG=&quot;0&quot; /&gt;
        '''   [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property O2Mania_Theme() As String
            Get
                Return ResourceManager.GetString("O2Mania_Theme", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Shortcut() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Shortcut", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Statistics3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Statistics3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TransparentBG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TransparentBG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WAVLeft() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WAVLeft", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WAVOffset() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WAVOffset", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WAVPrecision() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WAVPrecision", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WAVSaturation() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WAVSaturation", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WAVTransparency() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WAVTransparency", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WAVWidth() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WAVWidth", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property x16About() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x16About", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property x16Add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x16Add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property x16Associate() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x16Associate", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property x16CheckError() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x16CheckError", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property x16CheckErrorN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x16CheckErrorN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property x16Copy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x16Copy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property x16Cut() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x16Cut", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property x16Down() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x16Down", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property x16Export() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x16Export", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property x16Export2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x16Export2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property x16Find() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x16Find", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property x16GeneralOptions() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x16GeneralOptions", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property x16Help() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x16Help", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property x16Import() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x16Import", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property x16Import2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x16Import2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property x16Language() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x16Language", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property x16LnBMSE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x16LnBMSE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property x16LnNT() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x16LnNT", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property x16Lock() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x16Lock", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property x16MeasureInsert() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x16MeasureInsert", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property x16MeasureRemove() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x16MeasureRemove", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property x16Mirror() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x16Mirror", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property x16ModifyLabel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x16ModifyLabel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property x16ModifyLabelN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x16ModifyLabelN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property x16ModifyLabelY() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x16ModifyLabelY", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property x16MultiSelect() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x16MultiSelect", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property x16MyO2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x16MyO2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property x16New() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x16New", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property x16NewFromCode() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x16NewFromCode", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property x16NTInput() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x16NTInput", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property x16Open() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x16Open", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property x16Paste() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x16Paste", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property x16Pen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x16Pen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property x16Play() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x16Play", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property x16PlayB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x16PlayB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property x16PlayerBrowse() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x16PlayerBrowse", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property x16PlayerDefault() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x16PlayerDefault", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property x16PlayerOptions() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x16PlayerOptions", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property x16PreviewCheck() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x16PreviewCheck", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property x16PreviewCheckN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x16PreviewCheckN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property x16PreviewOnClick() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x16PreviewOnClick", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property x16PreviewOnClickN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x16PreviewOnClickN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property x16Redo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x16Redo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property x16Refresh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x16Refresh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property x16Remove() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x16Remove", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property x16Save() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x16Save", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property x16SaveAs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x16SaveAs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property x16Select() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x16Select", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property x16settings() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x16settings", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property x16ShowFileName() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x16ShowFileName", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property x16ShowFileNameN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x16ShowFileNameN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property x16Statistics() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x16Statistics", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property x16Stop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x16Stop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property x16Storm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x16Storm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property x16Theme() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x16Theme", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property x16TimeSelection() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x16TimeSelection", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property x16Undo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x16Undo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property x16Up() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x16Up", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property x16VisualOptions() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x16VisualOptions", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
